-- =============================================================================
-- Sentinel — Supabase PostgreSQL Schema
-- =============================================================================
-- Run this entire file in:
--   Supabase Dashboard → your project → SQL Editor → New Query → Run
--
-- All id columns use BIGINT PRIMARY KEY (not BIGSERIAL) so that Sentinel can
-- upsert rows using the exact same numeric IDs generated by local SQLite.
-- No foreign keys are declared here to keep sync ordering simple and resilient.
-- =============================================================================


-- ─── targets ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.targets (
    user_id  TEXT    PRIMARY KEY,
    added_at BIGINT  NOT NULL,
    label    TEXT,
    notes    TEXT,
    priority INTEGER DEFAULT 0,
    active   INTEGER DEFAULT 1
);

-- ─── events ──────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.events (
    id         BIGINT PRIMARY KEY,
    target_id  TEXT   NOT NULL,
    event_type TEXT   NOT NULL,
    timestamp  BIGINT NOT NULL,
    data       TEXT   NOT NULL,
    guild_id   TEXT,
    channel_id TEXT
);

CREATE INDEX IF NOT EXISTS idx_events_target    ON public.events (target_id, timestamp);
CREATE INDEX IF NOT EXISTS idx_events_type      ON public.events (event_type, timestamp);
CREATE INDEX IF NOT EXISTS idx_events_timestamp ON public.events (timestamp);
CREATE INDEX IF NOT EXISTS idx_events_guild     ON public.events (guild_id,   timestamp);
CREATE INDEX IF NOT EXISTS idx_events_channel   ON public.events (channel_id, timestamp);

-- ─── profile_snapshots ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.profile_snapshots (
    id                 BIGINT  PRIMARY KEY,
    target_id          TEXT    NOT NULL,
    timestamp          BIGINT  NOT NULL,
    username           TEXT,
    global_name        TEXT,
    discriminator      TEXT,
    avatar_hash        TEXT,
    banner_hash        TEXT,
    bio                TEXT,
    pronouns           TEXT,
    accent_color       INTEGER,
    connected_accounts TEXT,
    mutual_guilds      TEXT
);

CREATE INDEX IF NOT EXISTS idx_snapshots_target
    ON public.profile_snapshots (target_id, timestamp);

-- ─── presence_sessions ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.presence_sessions (
    id          BIGINT PRIMARY KEY,
    target_id   TEXT   NOT NULL,
    status      TEXT   NOT NULL,
    platform    TEXT,
    start_time  BIGINT NOT NULL,
    end_time    BIGINT,
    duration_ms BIGINT
);

CREATE INDEX IF NOT EXISTS idx_presence_target
    ON public.presence_sessions (target_id, start_time);

-- ─── activity_sessions ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.activity_sessions (
    id             BIGINT  PRIMARY KEY,
    target_id      TEXT    NOT NULL,
    activity_name  TEXT    NOT NULL,
    activity_type  INTEGER NOT NULL,
    application_id TEXT,
    details        TEXT,
    state          TEXT,
    start_time     BIGINT  NOT NULL,
    end_time       BIGINT,
    duration_ms    BIGINT,
    metadata       TEXT
);

CREATE INDEX IF NOT EXISTS idx_activity_target
    ON public.activity_sessions (target_id,      start_time);
CREATE INDEX IF NOT EXISTS idx_activity_name
    ON public.activity_sessions (activity_name,  start_time);

-- ─── voice_sessions ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.voice_sessions (
    id              BIGINT  PRIMARY KEY,
    target_id       TEXT    NOT NULL,
    guild_id        TEXT    NOT NULL,
    channel_id      TEXT    NOT NULL,
    channel_name    TEXT,
    start_time      BIGINT  NOT NULL,
    end_time        BIGINT,
    duration_ms     BIGINT,
    self_mute       INTEGER DEFAULT 0,
    self_deaf       INTEGER DEFAULT 0,
    server_mute     INTEGER DEFAULT 0,
    server_deaf     INTEGER DEFAULT 0,
    streaming       INTEGER DEFAULT 0,
    co_participants TEXT
);

CREATE INDEX IF NOT EXISTS idx_voice_target
    ON public.voice_sessions (target_id, start_time);

-- ─── messages ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.messages (
    message_id          TEXT    PRIMARY KEY,
    target_id           TEXT    NOT NULL,
    channel_id          TEXT    NOT NULL,
    guild_id            TEXT,
    content             TEXT,
    content_length      INTEGER,
    attachment_count    INTEGER DEFAULT 0,
    embed_count         INTEGER DEFAULT 0,
    has_sticker         INTEGER DEFAULT 0,
    is_reply            INTEGER DEFAULT 0,
    reply_to_user_id    TEXT,
    reply_to_message_id TEXT,
    created_at          BIGINT  NOT NULL,
    edited_at           BIGINT,
    deleted_at          BIGINT,
    edit_history        TEXT,
    word_count          INTEGER,
    emoji_count         INTEGER,
    mention_count       INTEGER,
    link_count          INTEGER
);

CREATE INDEX IF NOT EXISTS idx_messages_target
    ON public.messages (target_id,  created_at);
CREATE INDEX IF NOT EXISTS idx_messages_channel
    ON public.messages (channel_id, created_at);

-- ─── typing_events ───────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.typing_events (
    id                  BIGINT  PRIMARY KEY,
    target_id           TEXT    NOT NULL,
    channel_id          TEXT    NOT NULL,
    guild_id            TEXT,
    timestamp           BIGINT  NOT NULL,
    resulted_in_message INTEGER DEFAULT 0,
    message_delay_ms    INTEGER
);

CREATE INDEX IF NOT EXISTS idx_typing_target
    ON public.typing_events (target_id, timestamp);

-- ─── reactions ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.reactions (
    id                BIGINT  PRIMARY KEY,
    target_id         TEXT    NOT NULL,
    message_id        TEXT    NOT NULL,
    message_author_id TEXT,
    channel_id        TEXT    NOT NULL,
    guild_id          TEXT,
    emoji_name        TEXT    NOT NULL,
    emoji_id          TEXT,
    is_custom         INTEGER DEFAULT 0,
    added_at          BIGINT  NOT NULL,
    removed_at        BIGINT
);

CREATE INDEX IF NOT EXISTS idx_reactions_target
    ON public.reactions (target_id, added_at);

-- ─── guild_member_events ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.guild_member_events (
    id         BIGINT PRIMARY KEY,
    target_id  TEXT   NOT NULL,
    guild_id   TEXT   NOT NULL,
    event_type TEXT   NOT NULL,
    timestamp  BIGINT NOT NULL,
    old_value  TEXT,
    new_value  TEXT
);

-- ─── alert_rules ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.alert_rules (
    id         BIGINT  PRIMARY KEY,
    target_id  TEXT,
    rule_type  TEXT    NOT NULL,
    condition  TEXT    NOT NULL,
    enabled    INTEGER DEFAULT 1,
    created_at BIGINT  NOT NULL
);

-- ─── alert_history ───────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.alert_history (
    id           BIGINT  PRIMARY KEY,
    rule_id      BIGINT,
    target_id    TEXT    NOT NULL,
    alert_type   TEXT    NOT NULL,
    message      TEXT    NOT NULL,
    timestamp    BIGINT  NOT NULL,
    acknowledged INTEGER DEFAULT 0
);

-- ─── daily_summaries ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.daily_summaries (
    id               BIGINT  PRIMARY KEY,
    target_id        TEXT    NOT NULL,
    date             TEXT    NOT NULL,
    online_minutes   INTEGER DEFAULT 0,
    idle_minutes     INTEGER DEFAULT 0,
    dnd_minutes      INTEGER DEFAULT 0,
    offline_minutes  INTEGER DEFAULT 0,
    message_count    INTEGER DEFAULT 0,
    edit_count       INTEGER DEFAULT 0,
    delete_count     INTEGER DEFAULT 0,
    ghost_type_count INTEGER DEFAULT 0,
    voice_minutes    INTEGER DEFAULT 0,
    activity_minutes TEXT,
    reaction_count   INTEGER DEFAULT 0,
    first_seen       BIGINT,
    last_seen        BIGINT,
    peak_hour        INTEGER,
    UNIQUE (target_id, date)
);

CREATE INDEX IF NOT EXISTS idx_daily_target
    ON public.daily_summaries (target_id, date);


-- =============================================================================
-- Row Level Security
-- =============================================================================
-- Sentinel's selfbot uses the service-role key, which bypasses RLS entirely.
-- Disabling RLS here makes the intent explicit and simplifies any future
-- direct SQL access you might do from the Supabase dashboard.
-- =============================================================================

ALTER TABLE public.targets              DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.events               DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.profile_snapshots    DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.presence_sessions    DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_sessions    DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.voice_sessions       DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages             DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.typing_events        DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.reactions            DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.guild_member_events  DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.alert_rules          DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.alert_history        DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_summaries      DISABLE ROW LEVEL SECURITY;
